version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  lint_only:
    type: boolean
    default: true

jobs:
  lint:
    docker:
      - image: cimg/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install pre-commit hook
          command: |
            pip install pre-commit
            pre-commit install
      - run:
          name: Linting
          command: pre-commit run --all-files
      - run:
          name: Check docstring coverage
          command: |
            pip install interrogate
            interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 80 mmengine

  build_without_torch:
    parameters:
      # The python version must match available image tags in
      # https://circleci.com/developer/images/image/cimg/python
      python:
        type: string
        default: "3.7.4"
    docker:
      - image: cimg/python:<< parameters.python >>
    resource_class: large
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            pip install pip --upgrade
            pip --version
      - run:
          name: Build MMEngine from source
          command: pip install -e . -v
      - run:
          name: Install unit tests dependencies
          command: pip install -r requirements/tests_lite.txt
      - run:
          name: Run unit tests
          command: pytest tests/test_config tests/test_registry tests/test_fileio tests/test_logging tests/test_utils --ignore=tests/test_utils/test_dl_utils

  build_lite:
    parameters:
      # The python version must match available image tags in
      # https://circleci.com/developer/images/image/cimg/python
      python:
        type: string
        default: "3.7.4"
    docker:
      - image: cimg/python:<< parameters.python >>
    resource_class: large
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            pip install pip --upgrade
            pip --version
      - run:
          name: Build MMEngine from source
          command: MMENGINE_LITE=1 pip install -e . -v
      - run:
          name: Install unit tests dependencies
          command: pip install -r requirements/tests_lite.txt
      - run:
          name: Run unit tests
          command: pytest tests/test_config tests/test_registry tests/test_logging tests/test_utils --ignore=tests/test_utils/test_dl_utils

  build_cpu:
    parameters:
      # The python version must match available image tags in
      # https://circleci.com/developer/images/image/cimg/python
      python:
        type: string
      torch:
        type: string
      torchvision:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 libgl1-mesa-glx libjpeg-dev zlib1g-dev libtinfo-dev libncurses5
      - run:
          name: Configure Python & pip
          command: |
            pip install --upgrade pip
            pip install wheel
      - run:
          name: Install PyTorch
          command: pip install torch==<< parameters.torch >>+cpu torchvision==<< parameters.torchvision >>+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - run:
          name: Build MMEngine from source
          command: pip install -e . -v
      - run:
          name: Install unit tests dependencies
          command: |
            pip install -r requirements/tests.txt
      - run:
          name: Install mmcv
          command: |
            export PYTORCH=<< parameters.torch >>
            if [[ "${PYTORCH}" > "1.8.0" || "${PYTORCH}" == "1.8.0" ]]; then
              pip install openmim
              mim install mmcv
            fi
      - run:
          name: Run unittests
          command: |
            coverage run --branch --source mmengine -m pytest tests/
            coverage xml
            coverage report -m

  build_cuda:
    parameters:
      torch:
        type: string
      cuda:
        type: enum
        enum: ["10.1", "10.2", "11.1", "11.7", "11.8"]
      cudnn:
        type: integer
        default: 7
    machine:
      image: linux-cuda-11:default
      docker_layer_caching: true
    resource_class: gpu.nvidia.small.multi
    steps:
      - checkout
      - run:
          name: Install nvidia-container-toolkit and Restart Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y nvidia-container-toolkit
            sudo systemctl restart docker
      - run:
          name: Build Docker image
          command: |
            docker build .circleci/docker -t mmengine:gpu --build-arg PYTORCH=<< parameters.torch >> --build-arg CUDA=<< parameters.cuda >> --build-arg CUDNN=<< parameters.cudnn >>
            docker run --gpus all -t -d -v /home/circleci/project:/mmengine -e PYTORCH=<< parameters.torch >> -w /mmengine --name mmengine mmengine:gpu
      - run:
          name: Build MMEngine from source
          command: |
            docker exec mmengine pip install -e . -v
      - run:
          name: Install unit tests dependencies
          command: |
            docker exec mmengine pip install -r requirements/tests.txt
      - run:
          name: Install mmcv
          command: |
            if [[ "${PYTORCH}" > "1.8.0" || "${PYTORCH}" == "1.8.0" ]]; then
              docker exec mmengine pip install openmim
              docker exec mmengine mim install mmcv
            fi
      - run:
          name: Run unittests
          command: |
            docker exec mmengine python -m pytest tests/

  build_integration_test:
    parameters:
      torch:
        type: string
      cuda:
        type: string
      cudnn:
        type: integer
        default: 7
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
      docker_layer_caching: true
    resource_class: gpu.nvidia.small
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build .circleci/docker -t mmengine:gpu --build-arg PYTORCH=<< parameters.torch >> --build-arg CUDA=<< parameters.cuda >> --build-arg CUDNN=<< parameters.cudnn >>
            docker run --gpus all -t -d -v /home/circleci/project:/mmengine -w /mmengine --name mmengine mmengine:gpu
      - run:
          name: Build MMEngine from source
          command: |
            docker exec mmengine pip install -e . -v
      - run:
          name: Install unit tests dependencies
          command: |
            docker exec mmengine pip install -r requirements/tests.txt
            docker exec mmengine pip install openmim
            docker exec mmengine mim install mmcv
      - run:
          name: Install down stream repositories
          command: |
            docker exec mmengine mim install 'mmdet>=3.0.0rc0'
      - run:
          name: Run integration tests
          command: |
            docker exec mmengine pytest tests/test_infer/test_infer.py
      - run:
          name: Install down stream repositories from source
          # TODO: Switch to master branch
          command: |
            docker exec mmengine pip uninstall mmdet -y
            docker exec mmengine apt install git -y
            docker exec mmengine mkdir downstream_repos
            docker exec mmengine git clone -b 3.x https://github.com/open-mmlab/mmdetection.git ./downstream_repos/mmdetection
      - run:
          name: Run inferencer tests
          command: |
            docker exec -e PYTHONPATH=./downstream_repos/mmdetection mmengine pytest tests/test_infer/test_infer.py

workflows:
  pr_stage_lint:
    when: << pipeline.parameters.lint_only >>
    jobs:
      - lint:
          name: lint
          filters:
            branches:
              ignore:
                - main
  pr_stage_test:
    when:
      not:
        << pipeline.parameters.lint_only >>
    jobs:
      - lint:
          name: lint
          filters:
            branches:
              ignore:
                - main
      - build_lite:
          name: build lite
          requires:
            - lint
      - build_without_torch:
          name: build without torch
          requires:
            - lint
      - build_cpu:
          name: minimum_version_cpu
          torch: 1.6.0
          torchvision: 0.7.0
          python: 3.7.4
          requires:
            - lint
      - build_cpu:
          name: maximum_version_cpu
          torch: 2.1.0
          torchvision: 0.16.0
          python: 3.9.0
          requires:
            - minimum_version_cpu
      - hold_integration_test:
          type: approval
          requires:
            - lint
      - build_integration_test:
          name: integration_test
          torch: 1.8.1
          cuda: "10.2"
          requires:
            - hold_integration_test
      - hold:
          type: approval
          requires:
            - lint
      - build_cuda:
          name: mainstream_version_gpu
          torch: 1.8.1
          # Use double quotation mark to explicitly specify its type
          # as string instead of number
          cuda: "10.2"
          requires:
            - hold
      - build_cuda:
          name: maximum_version_gpu
          torch: 2.1.0
          cuda: "11.8"
          cudnn: 8
          requires:
            - hold
  merge_stage_test:
    when:
      not:
        << pipeline.parameters.lint_only >>
    jobs:
      - build_cuda:
          name: minimum_version_gpu
          torch: 1.6.0
          # Use double quotation mark to explicitly specify its type
          # as string instead of number
          cuda: "10.1"
          filters:
            branches:
              only:
                - main
