blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/open-mmlab/mmengine/discussions
    about: Ask general usage questions and discuss with other mmengine community members
  - name: MMEngine Documentation
    url: https://mmengine.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
  - name: ğŸŒ Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
